<?php

/**
 * PluginFileTrunkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFileTrunkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFileTrunkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFileTrunk');
    }
}